### ISSUE TITLE
Changing the devicetype of a already existing device with set properties throws error

### ISSUE THREAD

**Issue by thlenz** [OsnaCS/drk-funk#182]
German: Falls bei einem Device nicht alle Felder ausgefüllt sind kann eine Änderung der Devices nicht durchgeführt werden. Allerdings muss im vorraus ein Gerät mit Properties erstellt worden sein und danach dem Gerät einen neuen Typen zugeordnet werden mit weniger Properties als zuvor. Danach Value Error.

**Comment by elanfer** [comment]
@MatthiasGreshake please check this

**Comment by Mbrockmo** [comment]
@MatthiasGreshake wie weit?

**Comment by Mbrockmo** [comment]
fixed in commit d20f0e72799fca519f74900b2e7402835ab5a6d7
muss nochmal schöner gemacht werden

**Comment by MatthiasGreshake** [comment]
fixed CORRECTLY
