### ISSUE TITLE
if you saved the username and password in the browser every username and password field will be set on your own login datas

### ISSUE THREAD

**Issue by thlenz** [OsnaCS/drk-funk#186]
at creating a new user the password and username field will be set on your login data. Same in editing users but this only happens when there is no username or password in use

**Comment by ossovski** [comment]
probably a browser setting

**Comment by RaphaelMarx** [comment]
It seems like the new Browser versions do ignore the auto complete off option, therefore there is no bugfix available (yet)

**Comment by elanfer** [comment]
maybe fix in another milestone by using javascript but not in 0.2
~closed for now
