### ISSUE TITLE
db:reset Script isn't working @heroku

### ISSUE THREAD

**Issue by elanfer** [OsnaCS/drk-funk#203]
(0.9ms)  BEGIN
  SQL (1.1ms)  INSERT INTO "operations" ("location", "user_id", "operation_type", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["location", "Meppen"], ["user_id", 1], ["operation_type", "Operation_3"], ["created_at", "2015-09-16 08:23:23.705542"], ["updated_at", "2015-09-16 08:23:23.705542"]]
   (1.8ms)  COMMIT
  Device Load (1.4ms)  SELECT  "devices".* FROM "devices"  ORDER BY "devices"."id" DESC LIMIT 1
  User Load (1.4ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" ASC LIMIT 1
  User Load (1.3ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" DESC LIMIT 1
   (0.9ms)  BEGIN
  User Load (1.1ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 2]]
  User Load (1.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 1]]
  Device Load (1.2ms)  SELECT  "devices".* FROM "devices" WHERE "devices"."id" = $1 LIMIT 1  [["id", 2]]
  Lending Load (1.4ms)  SELECT "lendings".* FROM "lendings" WHERE (device_id = 2)
   (0.9ms)  ROLLBACK
rake aborted!
NoMethodError: undefined method `user' for true:TrueClass
/app/app/helpers/lendings_validator.rb:8:in `validate'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:455:in `public_send'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:455:in `block in make_lambda'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:182:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:182:in `block in conditional'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:504:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:504:in `block in call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:504:in `each'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:504:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_validate_callbacks'
/app/vendor/bundle/ruby/2.2.0/gems/activemodel-4.2.4/lib/active_model/validations.rb:398:in `run_validations!'
/app/vendor/bundle/ruby/2.2.0/gems/activemodel-4.2.4/lib/active_model/validations/callbacks.rb:113:in `block in run_validations!'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_validation_callbacks'
/app/vendor/bundle/ruby/2.2.0/gems/activemodel-4.2.4/lib/active_model/validations/callbacks.rb:113:in `run_validations!'
/app/vendor/bundle/ruby/2.2.0/gems/activemodel-4.2.4/lib/active_model/validations.rb:337:in `valid?'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/validations.rb:58:in `valid?'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/validations.rb:83:in `perform_validations'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/validations.rb:37:in `save'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/attribute_methods/dirty.rb:21:in `save'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:286:in `block (2 levels) in save'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:220:in `transaction'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:286:in `block in save'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:285:in `save'
/app/app/models/lending.rb:24:in `fill'
/app/db/seeds.rb:81:in `<top (required)>'

**Comment by elanfer** [comment]
@Mbrockmo your turn!

**Comment by Mbrockmo** [comment]
should be solved for now let's see whats the rest will do
