### ISSUE TITLE
wrong date type in device creation

### ISSUE THREAD

**Issue by Mbrockmo** [OsnaCS/drk-funk#215]
the current format looks like this "09/16/2015 1:10 PM"
and should look like this "2015-09-16 11:10:17" or "1442394617" for the db to work

**Comment by elanfer** [comment]
this is non critical and can be solved if there is a free time slot. Maybe @DanielKleine / @HendrikBrinkmann could have a look in this

**Comment by Mbrockmo** [comment]
this is a ploblem with creating a value of the datenote type this will not be picked up by our sceduler
