### ISSUE TITLE
Device_groups ente the barcode manually doesn't work 

### ISSUE THREAD

**Issue by thlenz** [OsnaCS/drk-funk#234]

**Comment by thlenz** [comment]
no errorhandling too

**Comment by elanfer** [comment]
error handling already got an an issue #232 
barcode will be fixed by @MatthiasGreshake and me

**Comment by MatthiasGreshake** [comment]
no knowledge about barcodes,
sounds like an eric-problem ;)

**Comment by elanfer** [comment]
works for me... @thlenz pleas show me the issue
