### ISSUE TITLE
it's possible to lend only ONE device even if i selected more than one. they aren't locked either for another lending

### ISSUE THREAD

**Issue by thlenz** [OsnaCS/drk-funk#238]

**Comment by elanfer** [comment]
last working revision was commit:374dfde

**Comment by elanfer** [comment]
@LenaScholz please compare the newest version with this one to locate the error 

the first bad commit where it was not working is:
commit 1a17167fa6d78e70d962e440e0ec352f60c45107
Author: Lena Scholz <lscholz@uos.de>
Date:   Fri Sep 11 14:50:24 2015 +0200

    Cleanup, reinsertion of lendings validation and reinsertion of form tags in lendings_selector

**Comment by elanfer** [comment]
commit 282f1ef
